#pragma config(Motor,  port1,           rightWheel1,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftWheel2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftWheel1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightWheel2,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]

void pre_auton()
{
  bStopTasksBetweenModes = true;

}

task autonomous()
{

}

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
    // Y component, X component, Rotation
		motor[leftWheel1]   = -C1LY - C1LX - C1RX;
		motor[rightWheel1]  =  C1LY - C1LX - C1RX;
		motor[rightWheel2]  =  C1LY + C1LX - C1RX;
		motor[leftWheel2]   = -C1LY + C1LX - C1RX;

		//Anywhere from 25-50 Msec pause
		wait1Msec(30);
	}
}
